### ISSUE TITLE
Allow for any bytes-like objects as input (e.g. memoryview)

### ISSUE THREAD

**Issue by llchan** [Iotic-Labs/py-lz4framed#11]
It would be beneficial to be able to pass in a buffer/memoryview without making a bytes copy. I think it would just involve using a different format string to the func arg parser (maybe `y*` if I'm reading this right?).

**Comment by vtermanis** [comment]
Yes, I think you might be right about `y*` (`s*` in Python v2). I'll have a look later this week.

**Comment by vtermanis** [comment]
@llchan - What's on the dev-contrib branch should hopefully do what you want (for `(de)compress` and `(de)compress_update` methods). Would you mind trying it out? If it works as you expect I can make a minor release with it.

**Comment by llchan** [comment]
Looks like it's working :)

Appreciate the quick turnaround!

**Comment by vtermanis** [comment]
Will be included in next release (at some point in near future).
