### ISSUE TITLE
Support passing memoryview objects

### ISSUE THREAD

**Issue by ssolari** [Iotic-Labs/py-lz4framed#12]
Use case
=======

We have a large pointer (memoryview) to a bytes buffer containing compressed data.  Specifically we are receiving and sending compressed py-lz4framed data via [zeromq zero-copy](http://zeromq.org/blog:zero-copy).   

It would be beneficial (and possibly more performant) if we did not have to create a copy of the bytes buffer (via .tobytes()) before we passed the data to py-lz4framed.   

Desired behavior
-----------------
  * decompress accepts memoryview object and does not create a copy of the input data
  * compress accepts memoryview object and does not copy the input data

I apologize that my C skills aren't good enough to submit a pull-request.

**Comment by vtermanis** [comment]
I think this is already addressed by https://github.com/Iotic-Labs/py-lz4framed/issues/11, but I haven't made a release with it yet.

I'll see whether I can make a release this evening for that.

**Comment by vtermanis** [comment]
v.0.9.7 should address your request hopefully. If not, please re-open this issue
