### ISSUE TITLE
Please never delete releases from PyPI

### ISSUE THREAD

**Issue by underyx** [Iotic-Labs/py-lz4framed#13]
Our build system broke since we were pinned to `py-lz4framed==0.9.5`, which has been deleted from `pypi.python.org`. It is a best practice to never delete released packages, to prevent such issues for people who were already using your library.

**Comment by vtermanis** [comment]
Sorry about that, my mistake! (I had been deleting test releases from test.pypi - should have left it at that.)

**Comment by underyx** [comment]
No worries, mistakes happen :)

Just wanted to make sure you're aware of it.
