### ISSUE TITLE
Duplicated effort

### ISSUE THREAD

**Issue by jonathanunderwood** [Iotic-Labs/py-lz4framed#14]
Hi folks at Iotic. I just stumbled across this package. We've been hard at work here building out lz4 frame bindings for Python (including file handlers etc): https://github.com/python-lz4/python-lz4

It's a shame to duplicate effort, hopefully we can collaborate :)

**Comment by vtermanis** [comment]
Hi @jonathanunderwood,
Did you have something particular in mind?

**Comment by vtermanis** [comment]
Please feel free to re-open if you have any suggestions.
