### ISSUE TITLE
level parameter <3 no effect

### ISSUE THREAD

**Issue by dreamflasher** [Iotic-Labs/py-lz4framed#6]
I wanted to benchmark different fast compression configurations, but setting the level to {0,1,2} makes no difference in file size.

**Comment by vtermanis** [comment]
I don't think this is an issue with py-lz4framed (I just pass all arguments through to the lz4 C library). I suspect for certain inputs it'll be the same and e.g. if you used the lz4 C library, it would behave the same as this module (I hope!).

If however this module does produce different output (compares to lz4 C library of same version), let me know. (Though I doubt that'll be the case.)

**Comment by dreamflasher** [comment]
Okay...
