### ISSUE TITLE
What causes Lz4FramedError (lz4framed.LZ4F_ERROR_GENERIC)

### ISSUE THREAD

**Issue by ghost** [Iotic-Labs/py-lz4framed#7]
Hi,

What does it mean error ('ERROR_GENERIC', 1)?

I wrote a piece of code that uses the TCP socket.
On one side I compresses data and send to the socket.
On other side I read.
The error occurs (on reader side) after I put too much, too quickly data to the socket.
Change block_size_id from LZ4F_BLOCKSIZE_MAX64KB to LZ4F_BLOCKSIZE_MAX4MB pushes the boundaries of the speed with which I can write.

Is this the expected error after exceeding the speed limit?

**Comment by vtermanis** [comment]
The errors are just passed through from what the C API returns, so e.g. that error could be due to a failure [here](https://github.com/lz4/lz4/blob/dev/lib/lz4frame.c#L1215) but if you search in that file you'll see there are a few places where it could occur.
I think it's fair to say that if this happens on decompression then somehow the compressed data is not reaching the other end fully (as you suggest).

You could try setting the [checksum](https://github.com/Iotic-Labs/py-lz4framed/blob/master/lz4framed/py-lz4framed.c#L210) flag on compression which, if the data is corrupted, should hopefully give you a [LZ4F_ERROR_headerChecksum_invalid or LZ4F_ERROR_headerChecksum_invalid](https://github.com/Iotic-Labs/py-lz4framed/blob/v0.9.5/lz4framed/py-lz4framed.c#L1035) instead of just [LZ4F_ERROR_GENERIC](https://github.com/Iotic-Labs/py-lz4framed/blob/v0.9.5/lz4framed/py-lz4framed.c#L1019) (e.g. see [here](https://github.com/lz4/lz4/blob/v1.7.5/lib/lz4frame.c#L1323) in the C lib).

**Comment by ghost** [comment]
I turned on the checksum and nothing has changed.

**Comment by vtermanis** [comment]
Can you post a snippet of your code to do with compression/decompression on gist [Gist](https://gist.github.com/)?
(Please bear in mind that I don't know the lz4 internals so unless it's something obvious I won't be able to help very much.)

**Comment by ghost** [comment]
```
== sender
ctx_writer = lz4framed.create_compression_context()
header = lz4framed.compress_begin(
	ctx_writer,
	block_size_id=lz4framed.LZ4F_BLOCKSIZE_MAX64KB,
	block_mode_linked=True,
	checksum=True,
	autoflush=True,
)
socket.send(header)

for data in random_data_generator():
	socket.send(
		lz4framed.compress_update(ctx_writer, data)
	)



== receiver
socket.read = socket.recv
for data in lz4framed.Decompressor(socket):
   print(data)
```

**Comment by vtermanis** [comment]
You still need to call `socket.send(compress_end(ctx_writer))` after sending all data (after the last `compress_update` call), e.g. like [here](https://github.com/Iotic-Labs/py-lz4framed/blob/master/lz4framed/__init__.py#L73). See also https://github.com/Iotic-Labs/py-lz4framed/blob/master/lz4framed/py-lz4framed.c#L691

However I couldn't reproduce the "generic" error, only specific ones (by making output shorter etc.). If you can save the raw output which produces the LZ4F_ERROR_GENERIC error, I could have a look.

**Comment by nri-pl** [comment]
I stripped everything to pieces and found the issue - gevent(Greenlet) + lz4framed.

Receiver code looks like this:
```
import lz4framed
import gevent
from gevent.server import StreamServer

def handler(conn, address):
	print('connect')
	for data in lz4framed.Decompressor(conn):
		pass

print('host-master started on port 3334')
server1 = StreamServer(('0.0.0.0', 3334), handler)
server1.serve_forever()
```

When the sender sends a very large amount of data for several seconds.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.4/dist-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "receiver.py", line 10, in handler
    for data in lz4framed.Decompressor(conn):
  File "/usr/local/lib/python3.4/dist-packages/py_lz4framed-0.9.5-py3.4-linux-x86_64.egg/lz4framed/__init__.py", line 199, in __iter__
    output = decompress_update(ctx, read(input_hint), chunk_size)
_lz4framed.Lz4FramedError: ('ERROR_GENERIC', 1)
Wed Mar  1 10:04:00 2017 <Greenlet at 0x7fe0dc443f20: _handle_and_close_when_done(<function handler at 0x7fe0dadb4bf8>, <bound method StreamServer.do_close of <StreamServ, (<gevent._socket3.socket [closed]  object, fd=-1, )> failed with Lz4FramedError
```

When resigns from gevent and Receiver code looks like below - everything works correctly.
```
import socket
import lz4framed

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
	s.bind(('0.0.0.0', 5555))
	s.listen(1)
	conn, addr = s.accept()

	with conn:
		print('Connected by', addr)
		for data in lz4framed.Decompressor(conn):
			pass

print('end')
```


Something is wrong when combined gevent and lz4framed and trying to gain maximum speed.
When I use small amounts of data (in relation to the link speed) everything works properly.
But when approaching the maximum bandwidth gevent states that the socket was closed and cat of data source for lz4framed.

**Comment by nri-pl** [comment]
However, this is not a issue with gevent.
I rewrite the code for threading and it is the same ...
Still I am looking for a reason ...

**Comment by ghost** [comment]
I finally found the cause.
The issue was on the sender side, instead of the receiver as I thought at the beginning.
Compressed data sent by socket.**send**() after the change to socket.**sendall** () the issue disappeared.

From Python docs "socket.send() ... if only some of the data was transmitted, the application needs to attempt delivery of the remaining data."
When I sent too much and too fast, I have to manually handle this at sender side or use sendall().

**Comment by vtermanis** [comment]
Nice to hear you found the cause!
